# Generated by Django 3.1.1 on 2021-06-04 08:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=1000)),
                ('quesDate', models.DateField(default=datetime.datetime(2021, 6, 4, 14, 3, 13, 122311))),
                ('activeStatus', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=5000)),
                ('ansDate', models.DateField(default=datetime.datetime(2021, 6, 4, 14, 3, 13, 124314))),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Question.studentquestion')),
            ],
        ),
    ]
